spring.application.name=smartcontactmanager

#Jdbc configuration includes, sessioFactory bean properties-> datasource, hibernate 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/smartcontactmanager_springboot
spring.datasource.username=root
spring.datasource.password=Sh1234567@
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update


